### ISSUE TITLE
Not working on Chromium 79??

### ISSUE THREAD

**Issue by masakre** [mallowigi/material-dev-tools#10]
I select a theme, close and open again DevTools and nothing happens, devtools keeps the original theme.

**Comment by OnkelTem** [comment]
Google Chrome here, the same.

**Comment by masakre** [comment]
@OnkelTem i got it working in my Chrome & Brave browser, not in Chromium do.
Check this steps provided in the Chrome Extension Store description:

Installation:

To use this theme, you'll need first to enable Developer Tools experiments in chrome://flags:
- Go to chrome://flags
- Look for "Developer Tools experiments"
- Enable it and restart Chrome
- Open Developer Tools
- Open the Settings > Experiments > "Allow Custom UI Themes"
- Close and reopen the DevTools

**Comment by OnkelTem** [comment]
@masakre Thanks, it works now! Honestly I haven't seen any instructions, missed them somehow. It works now.

**Comment by bjsteven** [comment]
I could not find the  "Developer Tools experiments" in flags list, and I setting " Experiments > "Allow Custom UI Themes", but it does not working.
Chrome 87.0.4280.27 and windows 10

**Comment by Drarox** [comment]
> @OnkelTem i got it working in my Chrome & Brave browser, not in Chromium do. Check this steps provided in the Chrome 

How did you get it to work on brave ? I only have an option "Allow extensions to load custom sylesheets" in the Experiments tab of the devtools Settings but it doesn't work with that.
