### ISSUE TITLE
Tab elements are being cut off when enabling chrome devtools.

### ISSUE THREAD

**Issue by jimmymain** [mallowigi/material-dev-tools#12]
The tab(s) are being cut off and have three dots instead of the full tab name(s).
This happens even when the screen is maxiumized.

![image](https://user-images.githubusercontent.com/2555050/80361006-8104fa80-8880-11ea-981a-36aafbf8302e.png)

**Comment by darkobits** [comment]
Also experiencing this issue on Chromium `81.0.4044.138`. 😢

**Comment by jimmymain** [comment]
is this an issue with the fact that chrome dev tools plugins are work in progress, or is it an issue with the material-dev-tools itself?

**Comment by mallowigi** [comment]
I'm not on Windows unfortunately, so I can't debug this right now. If someone is willing to help that'd be appreciated.

**Comment by mallowigi** [comment]
i think i fixed it, will be on version 4.0

**Comment by callmeberzerker** [comment]
This is still not fixed right?
