### ISSUE TITLE
Set different color for consoles debug and info logs

### ISSUE THREAD

**Issue by Ivan-rino** [mallowigi/material-dev-tools#15]
![image](https://user-images.githubusercontent.com/17064575/88928250-e3530a00-d278-11ea-9e09-fe2a1f03407e.png)

**Comment by mallowigi** [comment]
https://developer.chrome.com/docs/devtools/console/api/

From what I can see, debug, log and info are the same, so there's nothing we can do.

**Comment by Ivan-rino** [comment]
Hi @mallowigi!

I just checked that debugs have different color in the dark mode:

![image](https://user-images.githubusercontent.com/17064575/132695094-093135d9-1a7d-4325-96e7-110d13051de5.png)
