### ISSUE TITLE
Text selection is hard to see with dark(er) themes

### ISSUE THREAD

**Issue by randy** [mallowigi/material-dev-tools#16]
When using darker themes like Material Deep Ocean, Material Darker, and Night Owl, it is difficult to distinguish what is highlighted when selecting text. This is an issue in the "source" area as well as the command line.

This is unhighlighted text in Deep Ocean:
![image](https://user-images.githubusercontent.com/22246488/92164186-8cea6580-edfa-11ea-9c6c-3cade89ab5d4.png)

This is highlighted text in Deep Ocean (the whole line is highlighted. Please forgive the yellow line at the top, that's from a warning):
![image](https://user-images.githubusercontent.com/22246488/92164211-9a075480-edfa-11ea-9648-d5a60b79de3a.png)

This issue isn't as apparent for themes like Monokai Pro, Dracula, Arc Dark, and Atom One Dark. However, in light themes, the contrast between the background, foreground, and highlighting is much greater. I'm just hoping something similar can be done for the (awesome) darker themes.

**Comment by mallowigi** [comment]
I had this issue as well but I think I fixed it at some point. In any case I improved the contrast a bit, hope it's a bit better.
