### ISSUE TITLE
Choose a dark and a light theme

### ISSUE THREAD

**Issue by CharlieEtienne** [mallowigi/material-dev-tools#21]
Hi, I found that when Chrome DevTools theme is set to "Light" and Material Dev Tools is set to a dark theme, it uses the default devtools theme.
It would be nice to be able to select a light theme when it's light and a dark theme when it's dark.

Thanks,

Charlie

**Comment by mallowigi** [comment]
Unfortunately my options are pretty limited... I'm afraid the only way to do so is to change the theme manually when switching from light to dark and vice-versa
