### ISSUE TITLE
Something is covering devtools when resizing anything

### ISSUE THREAD

**Issue by iCrowned** [mallowigi/material-dev-tools#34]
When I try to resize any field quickly, the big square covers all my devtools panel, but then, when I stop doing it, it returns to a normal state
<img width="1064" alt="ScreenShot Google Chrome 2021-06-26" src="https://user-images.githubusercontent.com/80093436/123509871-b07be680-d680-11eb-984e-66a24ca4114e.png">
<img width="989" alt="ScreenShot Google Chrome 2021-06-26" src="https://user-images.githubusercontent.com/80093436/123509881-c7bad400-d680-11eb-9e6c-8c6442568495.png">
<img width="996" alt="ScreenShot Google Chrome 2021-06-26" src="https://user-images.githubusercontent.com/80093436/123509886-d0aba580-d680-11eb-983e-550f7606db18.png">

**Comment by mallowigi** [comment]
Yes, there is the only workaround i found to automatically theme the windows that got appended lazily. It's a bit annoying but it's better than having windows unthemed.
