### ISSUE TITLE
font style

### ISSUE THREAD

**Issue by 5alidshammout** [mallowigi/material-dev-tools#40]
bold, italic, etc. they are a nice idea

**Comment by 5alidshammout** [comment]
css: `font-style: bold`

**Comment by mallowigi** [comment]
I tried to see how it looks but I'm not really satisfied, so for now I am rejecting it. If you manage to find a way to make it looks better, please send me a screenshot of what you mean.

![CleanShot 2021-12-17 at 15 21 48](https://user-images.githubusercontent.com/5015756/146550894-0ff7ac7d-39c9-4bdb-af2f-50fe63002766.png)
