### ISSUE TITLE
Group counter in console unreadable.

### ISSUE THREAD

**Issue by tjacker** [mallowigi/material-dev-tools#52]
The group counter in the console is not styled correctly and is essentially unreadable. I am using version 4.0 of the extension and Chrome version 92. This issue exists on both MacOS Big Sur and Windows 10. Could you please look into this? Thank you.

<img src="https://user-images.githubusercontent.com/13052642/131007800-e8aff997-1392-41d3-aa1b-d32f3fac0625.png" width="252" />

**Comment by mallowigi** [comment]
Hi, can you provide reproducible steps? I tried to look but couldn't find info about "group counter"

**Comment by tjacker** [comment]
Hello, this is related to the "Group similar messages in console" setting in Chrome developer tools where instead of console logging the same message repeatedly, the console instead increments a count the left of the message being logged.

<img width="353" alt="Console_API_reference" src="https://user-images.githubusercontent.com/13052642/146805221-752c7f61-2dfb-462e-ba75-0de0df31e909.png">

**Comment by tjacker** [comment]
This is how the grouped messages appear with the extension disabled.

<img width="474" alt="example" src="https://user-images.githubusercontent.com/13052642/146806147-5aea3c09-2b32-47ea-aa34-7e5f3e985d3b.png">

**Comment by mallowigi** [comment]
Ok thank you, that's helpful for debugging

**Comment by shivajreddy** [comment]
> The group counter in the console is not styled correctly and is essentially unreadable. I am using version 4.0 of the extension and Chrome version 92. This issue exists on both MacOS Big Sur and Windows 10. Could you please look into this? Thank you.
> 
> <img alt="" width="252" src="https://user-images.githubusercontent.com/13052642/131007800-e8aff997-1392-41d3-aa1b-d32f3fac0625.png">

Please look into it, and adjust the background color of the counter, so that we can see the counter number

**Comment by mallowigi** [comment]
submitte
