### ISSUE TITLE
The background colors from the theme are partially applied. 

### ISSUE THREAD

**Issue by haosmos** [mallowigi/material-dev-tools#60]
First of all - thanks for the awesome tool! 

I am using the Material Design theme (Oceanic).
In the devtools settings, I chose the theme: "chromium dark".

For some reason the extension does not work quite correctly: in the "elements" tab, apparently, the color style of the background is not applied and is displayed as default, although next to it, in the properties panel, the correct background color is displayed. In the console tab, you can also see that the correct theme color is only applied to the input field, while the rest of the color is the default. But the other tabs are displayed with the correct background color. 

![msedge_fXe0lvNPuo](https://user-images.githubusercontent.com/30666874/133944604-dbf0d0dd-e7dd-4c93-a498-410bc5c5896a.png)

![msedge_UaUOXuJbQl](https://user-images.githubusercontent.com/30666874/133944608-bcd535ae-9f63-45dd-94fa-715a0f146ebd.png)

![msedge_QZ3GkYrMQF](https://user-images.githubusercontent.com/30666874/133944615-1420fc6c-2d41-4767-8bb8-e3582dd1f968.png)

![msedge_JzNtTaVtXi](https://user-images.githubusercontent.com/30666874/133944618-dcdfd88b-5af1-45e3-8bee-123708f15de0.png)

![msedge_U83vImtF7x](https://user-images.githubusercontent.com/30666874/133944623-3ffbb6b7-e726-4d40-b8b7-f682fb34405a.png)

I note that before this extension worked without problems for several years, I think. 
What happened now and why it stopped working is a complete mystery to me. 
What could be the reason and do you have any idea how I can make the theme display correctly? 

my environment: 
microsoft edge canary 95.0.1018.0
windows 11 pro (22000.194 build).

Let me please separately again that I have been using microsoft edge canary along with your extension for several years now and there have been no such problems before.

**Comment by mallowigi** [comment]
I have to say that I have to catch up with latest versions of Chrome/Chromium. I'm still in 90 and haven't updated yet, but I'm very busy so it will happen only after I can go back to this project.

**Comment by mallowigi** [comment]
should be fixed now
