### ISSUE TITLE
Don't modify scrollbar style on macOS

### ISSUE THREAD

**Issue by kidonng** [mallowigi/material-dev-tools#77]
By default, macOS's scrollbar floats on the page and only shows when scrolling:

![](https://i2.wp.com/css-tricks.com/wp-content/uploads/2018/11/scrollbar-02.gif?ssl=1) (Source: [CSS-Tricks](https://css-tricks.com/almanac/properties/s/scrollbar-gutter/))

A colored scrollbar may make sense on other platforms, but not so on macOS. I suggest only enable scrollbar style modification when the platform is not macOS.

**Comment by mallowigi** [comment]
There's no way to do what you want. Try without the extension and you'll see that the scrollbars are there.

**Comment by kidonng** [comment]
> There's no way to do what you want.

Just inject the scrollbar style when not on macOS? I didn't read the code but it should be possible.

> Try without the extension and you'll see that the scrollbars are there.

It's not like I've never seen a scrollbar in DevTools on macOS:

https://user-images.githubusercontent.com/44045911/140542930-0761ba9d-83d6-4def-9622-513bc834d8bf.mov

**Comment by kidonng** [comment]
Thanks for reopening! Yeah I realized this is a particularly niche request so if you don't bother to do it in the recent future, I may submit a PR myself.

**Comment by mallowigi** [comment]
interesting, I can't reproduce on my end. Maybe my chrome version is outdated, let me check on a newer version

**Comment by mallowigi** [comment]
However, I won't do what you want, but I'll try to investigate on how to reproduce the "disappearing scrollbar" behaviour

**Comment by kidonng** [comment]
> interesting, I can't reproduce on my end.

Maybe you have it disabled on the system settings, see https://osxdaily.com/2011/08/03/show-scroll-bars-mac-os-x-lion/ (choose any option other than "Always").

> However, I won't do what you want, but I'll try to investigate on how to reproduce the "disappearing scrollbar" behaviour

If you do want to theme the scrollbar, then sure, that would also be helpful.

**Comment by mallowigi** [comment]
I've found a class named `.platform-mac`, so there could be something related to it.

Anyway, I'm a bit busy in other projects at the moment, so sadly this won't be happening in the near future... If you want you can try to investigate yourself and do a PR tho.
