### ISSUE TITLE
Installation documentation is outdated

### ISSUE THREAD

**Issue by kidonng** [mallowigi/material-dev-tools#78]
[The installation documentation](https://material-theme.com/docs/other-products/#installation) is still using [info from almost 2 years ago](https://github.com/mallowigi/material-dev-tools/issues/10#issuecomment-575885742). On the latest version of Chrome, there's no need to enable "Developer Tools experiments" manually and "Allow Custom UI Themes" has been renamed to "Allow extensions to load custom stylesheets".

An updated steps would be:

1. Install the extension and choose a theme
2. Open DevTools
3. Open "Settings > Experiments" and select "Allow extensions to load custom stylesheets"
4. Restart and profit

**Comment by mike-lischke** [comment]
Even with your updated instructions I do not get custom theme support in my Chrom on macOS:

![Bildschirmfoto 2021-11-19 um 10 52 09](https://user-images.githubusercontent.com/2398704/142602769-90703ea3-8840-4d91-a260-5a39c613c559.png)

![Bildschirmfoto 2021-11-19 um 10 52 20](https://user-images.githubusercontent.com/2398704/142602785-8c204a0e-8067-41a2-97b8-f0dd532f4fdb.png)

Is there anything else required to make this work?

**Comment by kidonng** [comment]
Not quite part of _installation_ documentation but sure, that's nice to be added.

**Comment by rwkyyy** [comment]
as a new user, I can confirm, this helped me make the extension work!

**Comment by mike-lischke** [comment]
@mallowigi Can you please add where to find the theme settings (`Settings -> Preferences -> Theme`) in your installation instructions. This is set in a different place than where you enable custom style sheets, so I think this is valuable information too.

**Comment by mallowigi** [comment]
What do you mean? This is set via the Extension Options, is it not?

**Comment by mike-lischke** [comment]
In your description you have:

> If you use a dark theme (Oceanic, Palenight etc), select the Dark Mode, otherwise select the Light Mode

but you did not mention *where* to select the mode. So I suggested to add the info where to find the theme settings. For newcomers, try theme settings the first time (as it was for me), they don't know that the mode must be set or they do not see any effect of the installed theme.

**Comment by mallowigi** [comment]
I have published a new version that is not yet published, with the new texts. Once it is published I'll try to add more stuff.
