### ISSUE TITLE
Light theme issues

### ISSUE THREAD

**Issue by kidonng** [mallowigi/material-dev-tools#79]
Thanks for maintaining such an awesome extension (and particularly since there's no real alternative at the moment). Apart from some other feedbacks I submitted, this one is a real bug.

While most people prefer dark themes, I choose to use match the theme with rest of my system, and there are some issues with the light themes:

- **Atom One Light** theme uses dark border
  <img width="557" alt="截屏2021-11-06 00 12 04" src="https://user-images.githubusercontent.com/44045911/140544653-c1455ab7-9faa-4548-949c-c8c475f8d0de.png">
- Some text is not very legible with **GitHub** theme
  <img width="556" alt="截屏2021-11-06 00 10 46" src="https://user-images.githubusercontent.com/44045911/140544697-a56cdd1a-f140-4382-8484-3480b569e8d0.png">
- Close button on the DevTools settings page is white and almost invisible, this applies to all light themes including the (relatively) well-baheved **Material Lighter** theme
  <img width="555" alt="截屏2021-11-06 00 09 38" src="https://user-images.githubusercontent.com/44045911/140544688-b9bf4382-fa7f-4d59-9511-66c8924d8224.png">

**Comment by mallowigi** [comment]
Yeah, I tend to not check light themes because I'm not a real user, I expect them to work just like the dark themes but I didn't suspect so many ui issues.

**Comment by mallowigi** [comment]
Fixed
