### ISSUE TITLE
Console nested arrows displaying wrong

### ISSUE THREAD

**Issue by ekfuhrmann** [mallowigi/material-dev-tools#8]
Without expanding an object, you get the following in console:
![image](https://user-images.githubusercontent.com/8878152/67705513-8646c280-f98d-11e9-8435-f5cd57c25a7e.png)

Once expanded, the broken icons persist but are slightly askew:
![image](https://user-images.githubusercontent.com/8878152/67705574-a1193700-f98d-11e9-9487-8dfe5c4f3f1e.png)

**Comment by mallowigi** [comment]
You should have specified it from the get go...
